# Created with YamlCreate.ps1 v2.1.3 $debug=NVS1.5-1-22621-436
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: IBM.OpenJRE
PackageVersion: 18.0.2.9
MinimumOSVersion: 10.0.0.0
InstallerType: wix
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- java
FileExtensions:
- jar
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ibmruntimes/semeru18-binaries/releases/download/jdk-18.0.2%2B9_openj9-0.33.1/ibm-semeru-open-jre_x64_windows_18.0.2_9_openj9-0.33.1.msi
  InstallerSha256: 4AF3261763ED9328C5F21E3B624661081538C80E3A0A6AA37FA0F967836E2D0D
  ProductCode: '{02FE9C77-C01D-4FB0-9E63-EABEB4953CAC}'
ManifestType: installer
ManifestVersion: 1.2.0
